name: dynamic_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_gallery_assets: ^1.0.2

flutter:
  uses-material-design: true
  deferred-components: 
    - name: destinationFeature
      libraries:
        - package:dynamic_app/views/destinations/destinations_view.dart
      assets:
        - packages/flutter_gallery_assets/crane/destinations/eat_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/eat_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_0.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_11.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_12.jpg
        - packages/flutter_gallery_assets/crane/destinations/fly_13.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_0.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_1.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_2.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_3.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_4.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_5.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_6.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_7.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_8.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_9.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_10.jpg
        - packages/flutter_gallery_assets/crane/destinations/sleep_11.jpg
        - packages/flutter_gallery_assets/crane/logo/logo.png
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Medium.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-SemiBold.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Regular.ttf
        - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Light.ttf
